### ISSUE TITLE
PropertyCardModal.vue .toLocaleString breaks when there it is applied to null

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/property-data-explorer#158]

**Comment by stevetotheizz0** [comment]
I think this is because there is currently a choice to adding the required data sources to the options or not for the tables in the modal. 

I chose not to require the data sources bc it was less disruptive to show the empty table and populate it on the modal once the data source loads, as opposed to not having the table at all, and then having it load and change the page once the data source was available. 

A by product of showing the empty table is that the function attempts to run for the cell when there isn't a value yet. (And then runs again successfully once the data source is ready)
