### ISSUE TITLE
Result diff from AIS and shapeSearch

### ISSUE THREAD

**Issue by stevetotheizz0** [CityOfPhiladelphia/property-data-explorer#314]
1142 Frankford Ave

Somewhat similar to some of the other errors, this property works with an AIS search but returns an error from a shapeSearch

**Comment by ajrothwell** [comment]
when you do a shape search, it gets the parcel number from the store at shapeSearch.data.rows[0].parcel_number.

This is usually the OPA number

if it is NOT, then you get the error that you are seeing for 1142 Frankford Ave

**Comment by ajrothwell** [comment]
the data for shapeSearch.data.rows[0].parcel_number comes from:

https://phl.carto.com/api/v2/sql?q=select+*+from+opa_properties_public_test+where+pwd_parcel_id+IN(%2793907%27)

this is obviously not the final place that data should come from, at least because the table name is opa_properties_public_test

**Comment by danlopez** [comment]
Next step: Check whether there's an alternate table or if we need to do create a prod version of this table that is continually updated.
